### ISSUE TITLE
Uncaught Error: Class "League\Flysystem\Local\LocalFilesystemAdapter" not found 

### ISSUE THREAD

**Issue by aftabnaveed** [SanderSander/composer-link#25]
When trying to link my package I get this error

```
composer link ../php-packages/narwhal-layout

Fatal error: Uncaught Error: Class "League\Flysystem\Local\LocalFilesystemAdapter" not found in /var/cache/composer/vendor/sandersander/composer-link/src/Plugin.php:82
Stack trace:
#0 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(404): ComposerLink\Plugin->activate(Object(Composer\Composer), Object(Composer\IO\ConsoleIO))
#1 phar:///usr/bin/composer/src/Composer/Plugin/PluginManager.php(291): Composer\Plugin\PluginManager->addPlugin(Object(ComposerLink\Plugin), true, Object(Composer\Package\CompletePackage))

```

**Comment by SanderSander** [comment]
I released v0.2.0, you can use that version and it would be fixed! 😄 

Note that you need to run the link commands again when upgraded.
